sudo: false
language: java
jdk:
  - oraclejdk13

script:
  - ./gradlew -Dscan=true build

after_success:
  - ./gradlew check jacocoTestReport coveralls

after_failure:
  - ./gradlew clean check --debug